/**
 * Markdown Export Templates
 * Generate professional documentation from game concepts
 */

import type { MechanicsData, LoreData } from '@gameforge/shared';

/**
 * Generate Game Design Document (GDD)
 * Comprehensive format with all sections
 */
export function generateGDD(
  projectName: string,
  title: string,
  mechanics: MechanicsData,
  lore: LoreData,
  genre?: string,
  consistencyScore?: number
): string {
  return `# Game Design Document: ${title}

**Project:** ${projectName}
**Genre:** ${genre || 'Not specified'}
**Version:** 1.0
**Generated:** ${new Date().toLocaleDateString()}
${consistencyScore ? `**Consistency Score:** ${(consistencyScore * 100).toFixed(1)}%\n` : ''}

*Generated with GameForge Studio*

---

## Executive Summary

${title} is a ${genre || 'game'} that ${lore.setting?.worldType ? `takes place in ${lore.setting.worldType}` : 'features unique gameplay'}.

**Core Experience:** ${mechanics.coreLoop || 'Dynamic gameplay experience'}

---

## Game Overview

### Concept
${lore.conflict?.primary || 'An engaging interactive experience'}

### Target Audience
- Primary: ${genre === 'rpg' ? 'RPG enthusiasts' : genre === 'fps' ? 'Action gamers' : 'Gamers seeking innovative experiences'}
- Secondary: General gaming audience

### Unique Selling Points
${mechanics.playerActions ? mechanics.playerActions.slice(0, 3).map((a, i) => `${i + 1}. ${a}`).join('\n') : '1. Innovative gameplay\n2. Engaging mechanics\n3. Compelling narrative'}

---

## Narrative & Setting

### World
${lore.setting ? `
**Era:** ${lore.setting.era || 'TBD'}
**Location:** ${lore.setting.location || 'TBD'}
**World Type:** ${lore.setting.worldType || 'TBD'}
` : 'Setting to be determined'}

### World Rules
${lore.worldRules ? `
**Physics:** ${lore.worldRules.physics || 'Standard physics'}
**Magic:** ${lore.worldRules.magic || 'None'}
**Technology:** ${lore.worldRules.technology || 'Contemporary'}
` : 'World rules to be determined'}

### Story

**Protagonist:**
${lore.protagonist ? `
- **Background:** ${lore.protagonist.background || 'TBD'}
- **Motivation:** ${lore.protagonist.motivation || 'TBD'}
- **Abilities:** ${lore.protagonist.abilities?.join(', ') || 'TBD'}
` : 'Protagonist details to be determined'}

**Conflict:**
${lore.conflict ? `
- **Primary:** ${lore.conflict.primary || 'TBD'}
${lore.conflict.secondary ? `- **Secondary:** ${lore.conflict.secondary.join(', ')}` : ''}
` : 'Conflict to be determined'}

**Themes:**
${lore.themes && lore.themes.length > 0 ? lore.themes.map((t) => `- ${t}`).join('\n') : 'Themes to be explored'}

---

## Core Gameplay

### Core Loop
${mechanics.coreLoop || 'Core gameplay loop to be defined'}

### Player Actions
${mechanics.playerActions && mechanics.playerActions.length > 0 ? mechanics.playerActions.map((a) => `- ${a}`).join('\n') : 'Player actions to be defined'}

### Progression System
${mechanics.progressionSystems ? `
**Type:** ${mechanics.progressionSystems.type}
**Mechanics:** ${mechanics.progressionSystems.mechanics.join(', ')}
` : 'Progression system to be designed'}

### Win Conditions
${mechanics.winConditions && mechanics.winConditions.length > 0 ? mechanics.winConditions.map((w) => `- ${w}`).join('\n') : 'Victory conditions to be defined'}

### Fail Conditions
${mechanics.failConditions && mechanics.failConditions.length > 0 ? mechanics.failConditions.map((f) => `- ${f}`).join('\n') : 'Failure conditions to be defined'}

---

## Systems & Mechanics

### Resource Systems
${mechanics.resourceSystems && mechanics.resourceSystems.length > 0 ? mechanics.resourceSystems.map((r) => `
#### ${r.name}
- **Mechanics:** ${r.mechanics}
- **Scarcity:** ${r.scarcity}
`).join('\n') : 'Resource systems to be designed'}

---

## Technical Considerations

### Target Platforms
TBD - To be determined based on scope and budget

### Art Style
TBD - Should complement ${lore.setting?.worldType || 'the game concept'}

### Audio Direction
TBD - Music and sound effects to enhance ${lore.themes?.[0] || 'gameplay'}

---

## Development Roadmap

### Phase 1: Prototype
- Core mechanics implementation
- Basic art placeholders
- First playable build

### Phase 2: Alpha
- Full feature set
- Placeholder art and audio
- Internal testing

### Phase 3: Beta
- Final art and audio
- External testing
- Bug fixes and polish

### Phase 4: Release
- Final QA
- Marketing materials
- Launch

---

*This document was generated by GameForge Studio - AI-powered game concept generator*
`;
}

/**
 * Generate Pitch Deck
 * Condensed 2-page format for pitching
 */
export function generatePitch(
  projectName: string,
  title: string,
  mechanics: MechanicsData,
  lore: LoreData,
  genre?: string
): string {
  return `# ${title}
## Game Pitch

**Genre:** ${genre || 'Innovative Gaming Experience'}
**Platform:** Multi-platform (TBD)
**Target Audience:** ${genre === 'rpg' ? 'RPG Players' : genre === 'fps' ? 'Action Gamers' : 'Core Gamers'}

---

## The Hook

${lore.conflict?.primary || 'An innovative gaming experience that combines engaging mechanics with compelling narrative'}

---

## Core Gameplay

**In one sentence:** ${mechanics.coreLoop || 'Dynamic, engaging gameplay that keeps players coming back'}

**Key Features:**
${mechanics.playerActions ? mechanics.playerActions.slice(0, 5).map((a, i) => `${i + 1}. ${a}`).join('\n') : 'Innovative mechanics designed for maximum engagement'}

---

## The World

${lore.setting ? `Set in ${lore.setting.worldType || 'a unique world'} during ${lore.setting.era || 'an undefined era'}. ${lore.conflict?.primary || ''}` : 'A rich, immersive world awaits exploration'}

**Themes:** ${lore.themes?.join(', ') || 'Adventure, Discovery, Mastery'}

---

## Why This Game Will Succeed

1. **Unique Concept:** ${genre ? `Fresh take on ${genre} genre` : 'Innovative gameplay mechanics'}
2. **Market Opportunity:** Growing demand for quality ${genre || 'indie'} games
3. **Scalable Design:** Can start small and expand based on success

---

## Next Steps

1. Prototype development
2. Playtesting and iteration
3. Seek funding/publisher
4. Full production

---

**Contact:** [Your Contact Information]
*Pitch generated by GameForge Studio*
`;
}

/**
 * Generate Technical Specification
 * Developer-focused format
 */
export function generateTechnical(
  projectName: string,
  title: string,
  mechanics: MechanicsData,
  lore: LoreData,
  genre?: string
): string {
  return `# Technical Specification: ${title}

**Project:** ${projectName}
**Type:** ${genre || 'Game'} Development
**Date:** ${new Date().toLocaleDateString()}

---

## Technical Overview

### Core Systems

#### Gameplay Systems
${mechanics.playerActions ? mechanics.playerActions.map((a) => `- ${a} system`).join('\n') : 'Core gameplay systems'}

#### Progression System
${mechanics.progressionSystems ? `
**Type:** ${mechanics.progressionSystems.type}
**Implementation Requirements:**
${mechanics.progressionSystems.mechanics.map((m) => `- ${m}`).join('\n')}
` : 'Progression system architecture'}

#### Resource Management
${mechanics.resourceSystems ? mechanics.resourceSystems.map((r) => `
**${r.name}:**
- Scarcity: ${r.scarcity}
- Mechanics: ${r.mechanics}
`).join('\n') : 'Resource systems'}

---

## Game Logic

### Win Conditions
${mechanics.winConditions ? mechanics.winConditions.map((w) => `- ${w}`).join('\n') : 'Victory logic'}

### Fail Conditions
${mechanics.failConditions ? mechanics.failConditions.map((f) => `- ${f}`).join('\n') : 'Failure logic'}

---

## World Rules & Constraints

### Physics
${lore.worldRules?.physics || 'Standard physics simulation'}

### Magic System
${lore.worldRules?.magic || 'No magic system'}

### Technology Level
${lore.worldRules?.technology || 'Contemporary technology'}

---

## Data Structures

### Player State
\`\`\`typescript
interface PlayerState {
  ${lore.protagonist?.abilities ? lore.protagonist.abilities.map((a) => `${a.toLowerCase().replace(/\s+/g, '_')}: boolean;`).join('\n  ') : 'abilities: string[];'}
  ${mechanics.resourceSystems ? mechanics.resourceSystems.map((r) => `${r.name.toLowerCase().replace(/\s+/g, '_')}: number;`).join('\n  ') : 'resources: {}'}
}
\`\`\`

### Game State
\`\`\`typescript
interface GameState {
  ${mechanics.progressionSystems ? `progressionType: '${mechanics.progressionSystems.type}';` : 'progression: any;'}
  currentObjective: string;
  isComplete: boolean;
}
\`\`\`

---

## Implementation Notes

### Priority 1: Core Mechanics
${mechanics.coreLoop || 'Implement basic gameplay loop'}

### Priority 2: Progression
${mechanics.progressionSystems ? mechanics.progressionSystems.mechanics[0] : 'Add progression system'}

### Priority 3: Polish
- UI/UX refinement
- Audio integration
- Visual effects

---

*Technical spec generated by GameForge Studio*
`;
}
